server:
  port: 8032
  error:
    include-message: always
    include-binding-errors: always
resilience4j:
  circuitbreaker:
    instances:
      pasive-card-service:
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
  timelimiter:
    instances:
      pasive-card-service:
        timeout-duration: 2s
spring:
  data:
    mongodb:
      uri: mongodb+srv://sa:R35rPvm0XFgR8dIh@walter.iyabt.mongodb.net/bootcamp?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
