server:
  port: 8072
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      uri: mongodb+srv://nttdata:nttdata@nttdata.zm6n3.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
